apiVersion: v1
kind: Secret
metadata:
  name: {{ include "streambridge.backendName" . }}-env
  labels:
    {{- include "streambridge.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "streambridge.databaseUrl" . | quote }}
  TMDB_API_KEY: {{ .Values.backend.secrets.tmdbApiKey | quote }}
  ADMIN_USERNAME: {{ .Values.backend.secrets.adminUsername | quote }}
  ADMIN_PASSWORD: {{ .Values.backend.secrets.adminPassword | quote }}
  JWT_SECRET: {{ .Values.backend.secrets.jwtSecret | quote }}
  TWENTY_API_KEY: {{ .Values.backend.secrets.twentyApiKey | quote }}
  TWENTY_WEBHOOK_SECRET: {{ .Values.backend.secrets.twentyWebhookSecret | quote }}
  TWO_CAPTCHA_API_KEY: {{ .Values.backend.secrets.twoCaptchaApiKey | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.backend.secrets.googleClientId | quote }}
  RESEND_API_KEY: {{ .Values.backend.secrets.resendApiKey | quote }}
  RESEND_FROM_EMAIL: {{ .Values.backend.secrets.resendFromEmail | quote }}
  {{- if .Values.backend.secrets.paygateWalletAddress }}
  PAYGATE_WALLET_ADDRESS: {{ .Values.backend.secrets.paygateWalletAddress | quote }}
  {{- end }}
  {{- if .Values.vpn.enabled }}
  PIA_USERNAME: {{ .Values.backend.secrets.piaUsername | quote }}
  PIA_PASSWORD: {{ .Values.backend.secrets.piaPassword | quote }}
  {{- end }}
