apiVersion: v1
kind: Secret
metadata:
  name: {{ include "streambridge.backendName" . }}-env
  labels:
    {{- include "streambridge.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "streambridge.databaseUrl" . | quote }}
  TMDB_API_KEY: {{ .Values.backend.secrets.tmdbApiKey | quote }}
  ADMIN_USERNAME: {{ .Values.backend.secrets.adminUsername | quote }}
  ADMIN_PASSWORD: {{ .Values.backend.secrets.adminPassword | quote }}
  JWT_SECRET: {{ .Values.backend.secrets.jwtSecret | quote }}
  {{- if .Values.vpn.enabled }}
  PIA_USERNAME: {{ .Values.backend.secrets.piaUsername | quote }}
  PIA_PASSWORD: {{ .Values.backend.secrets.piaPassword | quote }}
  {{- end }}
