{{- if and .Values.postgres.enabled (not .Values.postgres.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "streambridge.postgresAuthSecretName" . }}
  labels:
    {{- include "streambridge.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.postgres.auth.secretKeys.database }}: {{ .Values.postgres.auth.database | quote }}
  {{ .Values.postgres.auth.secretKeys.username }}: {{ .Values.postgres.auth.username | quote }}
  {{ .Values.postgres.auth.secretKeys.password }}: {{ .Values.postgres.auth.password | quote }}
{{- end }}
